create table if not exists public.cotizacion_items (
  id uuid primary key default gen_random_uuid(),
  empresa_id uuid not null default public.current_empresa_id() references public.empresas(id) on delete cascade,
  cotizacion_id uuid not null references public.cotizaciones(id) on delete cascade,
  tipo text not null default 'servicio' check (tipo in ('servicio', 'repuesto', 'mano_obra', 'traslado', 'otro')),
  codigo text,
  descripcion text not null,
  cantidad numeric not null default 1,
  precio_unitario numeric not null default 0,
  descuento numeric not null default 0,
  total numeric not null default 0,
  orden integer not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.cotizacion_documentos (
  id bigint generated by default as identity primary key,
  empresa_id uuid not null default public.current_empresa_id() references public.empresas(id) on delete cascade,
  cotizacion_id uuid references public.cotizaciones(id) on delete set null,
  cliente_id uuid references public.clientes(id) on delete set null,
  contacto_id uuid references public.contactos(id) on delete set null,
  equipo_id uuid references public.machines(id) on delete set null,
  tipo text not null default 'PRE-COTIZACION',
  estado text not null default 'pre_cotizacion',
  pre_numero text,
  numero bigint,
  fecha_emision date,
  fecha_vcto date,
  rut_empresa text,
  cliente_nombre text,
  cliente_contacto text,
  cliente_rut text,
  cliente_direccion text,
  cliente_giro text,
  cliente_comuna text,
  cliente_telefono text,
  cliente_ciudad text,
  cliente_email text,
  referencia text,
  observaciones text,
  garantia text,
  condiciones text,
  items jsonb not null default '[]'::jsonb,
  subtotal numeric not null default 0,
  neto numeric not null default 0,
  iva numeric not null default 0,
  total numeric not null default 0,
  data jsonb not null default '{}'::jsonb,
  emitida_at timestamptz,
  created_by uuid references auth.users(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (empresa_id, numero),
  unique (empresa_id, pre_numero)
);

create or replace function public.next_erp_pre_cotizacion()
returns text
language plpgsql
security definer
set search_path = public
as '
declare
  target_empresa_id uuid;
  next_num bigint;
begin
  target_empresa_id := public.current_empresa_id();

  if target_empresa_id is null then
    raise exception ''Usuario sin empresa activa'';
  end if;

  insert into public.erp_counters (empresa_id, key, last_value)
  values (target_empresa_id, ''pre_cotizacion'', 0)
  on conflict (empresa_id, key) do nothing;

  update public.erp_counters
  set last_value = last_value + 1,
      updated_at = now()
  where empresa_id = target_empresa_id
    and key = ''pre_cotizacion''
  returning last_value into next_num;

  return ''PRE-'' || lpad(next_num::text, 5, ''0'');
end;
';

create or replace function public.next_erp_cotizacion()
returns bigint
language plpgsql
security definer
set search_path = public
as '
declare
  target_empresa_id uuid;
  next_num bigint;
begin
  target_empresa_id := public.current_empresa_id();

  if target_empresa_id is null then
    raise exception ''Usuario sin empresa activa'';
  end if;

  insert into public.erp_counters (empresa_id, key, last_value)
  values (target_empresa_id, ''cotizacion'', 11865)
  on conflict (empresa_id, key) do nothing;

  update public.erp_counters
  set last_value = last_value + 1,
      updated_at = now()
  where empresa_id = target_empresa_id
    and key = ''cotizacion''
  returning last_value into next_num;

  return next_num;
end;
';

create or replace function public.emit_erp_cotizacion(doc_id bigint)
returns public.cotizacion_documentos
language sql
security definer
set search_path = public
as '
  with target as (
    select id, numero
    from public.cotizacion_documentos
    where id = $1
      and public.is_empresa_member(empresa_id)
    for update
  ),
  next_number as (
    select
      case
        when exists (select 1 from target where numero is null)
        then public.next_erp_cotizacion()
      end as numero
  ),
  updated as (
    update public.cotizacion_documentos cd
    set numero = coalesce(cd.numero, next_number.numero),
        tipo = ''COTIZACION'',
        estado = ''cotizacion_emitida'',
        emitida_at = coalesce(cd.emitida_at, now()),
        updated_at = now(),
        data = coalesce(cd.data, ''{}''::jsonb)
          || jsonb_build_object(
            ''numero'', coalesce(cd.numero, next_number.numero)::text,
            ''tipo'', ''COTIZACION'',
            ''estado'', ''cotizacion_emitida'',
            ''numeroReservado'', true,
            ''dirty'', false,
            ''savedAt'', now()::text
          )
    from target, next_number
    where cd.id = target.id
    returning cd.*
  )
  select *
  from updated
';

create or replace function public.sync_cotizacion_documento_relaciones()
returns trigger
language plpgsql
security definer
set search_path = public
as '
begin
  if new.empresa_id is null then
    return new;
  end if;

  if new.cliente_id is null and nullif(trim(coalesce(new.cliente_nombre, '''')), '''') is not null then
    if nullif(trim(coalesce(new.cliente_rut, '''')), '''') is not null then
      new.cliente_id := (
        with upserted as (
          insert into public.clientes (
            empresa_id,
            razon_social,
            rut,
            giro,
            email,
            telefono,
            direccion,
            comuna,
            ciudad
          )
          values (
            new.empresa_id,
            trim(new.cliente_nombre),
            trim(new.cliente_rut),
            nullif(trim(coalesce(new.cliente_giro, '''')), ''''),
            nullif(trim(coalesce(new.cliente_email, '''')), ''''),
            nullif(trim(coalesce(new.cliente_telefono, '''')), ''''),
            nullif(trim(coalesce(new.cliente_direccion, '''')), ''''),
            nullif(trim(coalesce(new.cliente_comuna, '''')), ''''),
            nullif(trim(coalesce(new.cliente_ciudad, '''')), '''')
          )
          on conflict (empresa_id, rut) do update
            set razon_social = excluded.razon_social,
                giro = coalesce(excluded.giro, public.clientes.giro),
                email = coalesce(excluded.email, public.clientes.email),
                telefono = coalesce(excluded.telefono, public.clientes.telefono),
                direccion = coalesce(excluded.direccion, public.clientes.direccion),
                comuna = coalesce(excluded.comuna, public.clientes.comuna),
                ciudad = coalesce(excluded.ciudad, public.clientes.ciudad),
                updated_at = now()
          returning id
        )
        select id from upserted
      );
    else
      new.cliente_id := (
        select id
        from public.clientes
        where empresa_id = new.empresa_id
          and lower(razon_social) = lower(trim(new.cliente_nombre))
        order by created_at asc
        limit 1
      );

      if new.cliente_id is null then
        new.cliente_id := (
          with inserted as (
            insert into public.clientes (
              empresa_id,
              razon_social,
              email,
              telefono,
              direccion,
              comuna,
              ciudad
            )
            values (
              new.empresa_id,
              trim(new.cliente_nombre),
              nullif(trim(coalesce(new.cliente_email, '''')), ''''),
              nullif(trim(coalesce(new.cliente_telefono, '''')), ''''),
              nullif(trim(coalesce(new.cliente_direccion, '''')), ''''),
              nullif(trim(coalesce(new.cliente_comuna, '''')), ''''),
              nullif(trim(coalesce(new.cliente_ciudad, '''')), '''')
            )
            returning id
          )
          select id from inserted
        );
      end if;
    end if;
  end if;

  if new.cliente_id is not null
    and new.contacto_id is null
    and nullif(trim(coalesce(new.cliente_contacto, '''')), '''') is not null then

    if nullif(trim(coalesce(new.cliente_email, '''')), '''') is not null then
      new.contacto_id := (
        select id
        from public.contactos
        where empresa_id = new.empresa_id
          and cliente_id = new.cliente_id
          and lower(email) = lower(trim(new.cliente_email))
        order by created_at asc
        limit 1
      );
    end if;

    if new.contacto_id is null then
      new.contacto_id := (
        select id
        from public.contactos
        where empresa_id = new.empresa_id
          and cliente_id = new.cliente_id
          and lower(nombre) = lower(trim(new.cliente_contacto))
        order by created_at asc
        limit 1
      );
    end if;

    if new.contacto_id is null then
      new.contacto_id := (
        with inserted as (
          insert into public.contactos (
            empresa_id,
            cliente_id,
            nombre,
            email,
            telefono,
            principal
          )
          values (
            new.empresa_id,
            new.cliente_id,
            trim(new.cliente_contacto),
            nullif(trim(coalesce(new.cliente_email, '''')), ''''),
            nullif(trim(coalesce(new.cliente_telefono, '''')), ''''),
            true
          )
          returning id
        )
        select id from inserted
      );
    end if;
  end if;

  return new;
end;
';

create table if not exists public.ordenes_trabajo (
  id uuid primary key default gen_random_uuid(),
  empresa_id uuid not null default public.current_empresa_id() references public.empresas(id) on delete cascade,
  cliente_id uuid references public.clientes(id) on delete set null,
  contacto_id uuid references public.contactos(id) on delete set null,
  equipo_id uuid references public.machines(id) on delete set null,
  cotizacion_id uuid references public.cotizaciones(id) on delete set null,
  folio text not null,
  titulo text,
  estado text not null default 'recibida' check (estado in ('recibida', 'diagnostico', 'esperando_aprobacion', 'en_reparacion', 'pruebas', 'lista', 'entregada', 'cerrada', 'cancelada')),
  prioridad text not null default 'normal' check (prioridad in ('baja', 'normal', 'alta', 'urgente')),
  descripcion_problema text,
  diagnostico text,
  solucion text,
  responsable_id uuid references auth.users(id),
  fecha_ingreso timestamptz not null default now(),
  fecha_prometida date,
  fecha_cierre timestamptz,
  horas_estimadas numeric,
  horas_reales numeric,
  costo_estimado numeric,
  costo_real numeric,
  precio_final numeric,
  created_by uuid references auth.users(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (empresa_id, folio)
);

create or replace function public.crear_ot_desde_cotizacion_documento(doc_id bigint)
returns public.ordenes_trabajo
language sql
security definer
set search_path = public
as '
  with documento as (
    select *
    from public.cotizacion_documentos
    where id = $1
      and public.is_empresa_member(empresa_id)
  ),
  preparada as (
    select
      documento.*,
      ''OT-'' || coalesce(documento.numero::text, documento.pre_numero, documento.id::text) as folio_ot
    from documento
  ),
  creada as (
    insert into public.ordenes_trabajo (
      empresa_id,
      cliente_id,
      contacto_id,
      equipo_id,
      cotizacion_id,
      folio,
      titulo,
      estado,
      prioridad,
      descripcion_problema,
      created_by
    )
    select
      preparada.empresa_id,
      preparada.cliente_id,
      preparada.contacto_id,
      preparada.equipo_id,
      preparada.cotizacion_id,
      preparada.folio_ot,
      ''Servicio desde cotización '' || coalesce(preparada.numero::text, preparada.pre_numero, preparada.id::text),
      ''recibida'',
      ''normal'',
      nullif(trim(coalesce(preparada.referencia, preparada.observaciones, '''')), ''''),
      auth.uid()
    from preparada
    where not exists (
      select 1
      from public.ordenes_trabajo ot
      where ot.empresa_id = preparada.empresa_id
        and ot.folio = preparada.folio_ot
    )
    returning *
  ),
  existente as (
    select ot.*
    from public.ordenes_trabajo ot
    join preparada on preparada.empresa_id = ot.empresa_id
      and preparada.folio_ot = ot.folio
  )
  select *
  from creada
  union all
  select *
  from existente
  limit 1
';


create table if not exists public.audits (
  id uuid primary key default gen_random_uuid(),
  empresa_id uuid not null default public.current_empresa_id() references public.empresas(id) on delete cascade,
  equipo_id uuid references public.machines(id) on delete set null,
  title text not null,
  audit_type text not null default 'inventario' check (audit_type in ('inventario', 'mantencion', 'seguridad', 'general')),
  status text not null default 'pendiente' check (status in ('pendiente', 'en_proceso', 'completada', 'observada')),
  responsible text,
  scheduled_date date,
  completed_date date,
  notes text,
  created_by uuid references auth.users(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.equipo_eventos (
  id uuid primary key default gen_random_uuid(),
  empresa_id uuid not null default public.current_empresa_id() references public.empresas(id) on delete cascade,
  equipo_id uuid not null references public.machines(id) on delete cascade,
  orden_trabajo_id uuid references public.ordenes_trabajo(id) on delete set null,
  cotizacion_id uuid references public.cotizaciones(id) on delete set null,
  audit_id uuid references public.audits(id) on delete set null,
  tipo text not null default 'nota' check (tipo in ('ingreso', 'diagnostico', 'reparacion', 'prueba', 'entrega', 'auditoria', 'cambio_estado', 'foto', 'repuesto', 'nota')),
  titulo text not null,
  descripcion text,
  metadata jsonb not null default '{}'::jsonb,
  created_by uuid references auth.users(id),
  created_at timestamptz not null default now()
);

create table if not exists public.archivos (
  id uuid primary key default gen_random_uuid(),
  empresa_id uuid not null default public.current_empresa_id() references public.empresas(id) on delete cascade,
  entidad_tipo text not null check (entidad_tipo in ('cliente', 'equipo', 'cotizacion', 'orden_trabajo', 'auditoria', 'evento')),
  entidad_id uuid not null,
  bucket text not null default 'erp',
  path text not null,
  nombre text not null,
  mime_type text,
  size_bytes bigint,
  descripcion text,
  created_by uuid references auth.users(id),
  created_at timestamptz not null default now()
);

create table if not exists public.import_logs (
  id uuid primary key default gen_random_uuid(),
  empresa_id uuid not null default public.current_empresa_id() references public.empresas(id) on delete cascade,
  import_type text not null,
  total_rows integer not null default 0,
  success_rows integer not null default 0,
  error_rows integer not null default 0,
  metadata jsonb not null default '{}'::jsonb,
  created_by uuid references auth.users(id),
  created_at timestamptz not null default now()
);

create table if not exists public.personas (
  id uuid primary key default gen_random_uuid(),
  empresa_id uuid not null default public.current_empresa_id() references public.empresas(id) on delete cascade,
  tipo_relacion text not null default 'contrato' check (tipo_relacion in ('contrato', 'honorarios', 'proveedor', 'externo')),
  rut text,
  nombre text not null,
  email text,
  telefono text,
  direccion text,
  cargo text,
  centro_costo text,
  banco text,
  tipo_cuenta text,
  numero_cuenta text,
  activo boolean not null default true,
  notas text,
  created_by uuid references auth.users(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (empresa_id, rut)
);

create table if not exists public.pagos_personas (
  id uuid primary key default gen_random_uuid(),
  empresa_id uuid not null default public.current_empresa_id() references public.empresas(id) on delete cascade,
  persona_id uuid not null references public.personas(id) on delete cascade,
  periodo date not null default date_trunc('month', now())::date,
  tipo_pago text not null default 'sueldo' check (tipo_pago in ('sueldo', 'honorario', 'anticipo', 'bono', 'reembolso', 'comision', 'otro')),
  estado text not null default 'pendiente' check (estado in ('pendiente', 'aprobado', 'pagado', 'anulado')),
  bruto numeric not null default 0,
  retencion numeric not null default 0,
  descuentos numeric not null default 0,
  liquido numeric not null default 0,
  fecha_pago date,
  numero_documento text,
  documento_url text,
  comprobante_url text,
  notas text,
  detalle jsonb not null default '{}'::jsonb,
  created_by uuid references auth.users(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.documentos_personas (
  id uuid primary key default gen_random_uuid(),
  empresa_id uuid not null default public.current_empresa_id() references public.empresas(id) on delete cascade,
  persona_id uuid not null references public.personas(id) on delete cascade,
  pago_id uuid references public.pagos_personas(id) on delete set null,
  tipo text not null default 'liquidacion' check (tipo in ('liquidacion', 'boleta_honorarios', 'contrato', 'anexo', 'comprobante', 'otro')),
  periodo date,
  nombre text not null,
  url text,
  notas text,
  created_by uuid references auth.users(id),
  created_at timestamptz not null default now()
);

create table if not exists public.crm_oportunidades (
  id uuid primary key default gen_random_uuid(),
  empresa_id uuid not null default public.current_empresa_id() references public.empresas(id) on delete cascade,
  cliente_id uuid references public.clientes(id) on delete set null,
  contacto_id uuid references public.contactos(id) on delete set null,
  cotizacion_id uuid references public.cotizaciones(id) on delete set null,
  nombre text not null,
  etapa text not null default 'prospecto' check (etapa in ('prospecto', 'contactado', 'cotizando', 'negociacion', 'ganada', 'perdida')),
  valor_estimado numeric not null default 0,
  probabilidad integer not null default 0 check (probabilidad between 0 and 100),
  fecha_cierre_estimada date,
  responsable_id uuid references auth.users(id),
  notas text,
  created_by uuid references auth.users(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.whatsapp_mensajes (
  id uuid primary key default gen_random_uuid(),
  empresa_id uuid not null default public.current_empresa_id() references public.empresas(id) on delete cascade,
  cliente_id uuid references public.clientes(id) on delete set null,
  contacto_id uuid references public.contactos(id) on delete set null,
  orden_trabajo_id uuid references public.ordenes_trabajo(id) on delete set null,
  cotizacion_id uuid references public.cotizaciones(id) on delete set null,
  telefono text not null,
  plantilla text,
  mensaje text not null,
  estado text not null default 'pendiente' check (estado in ('pendiente', 'enviado', 'fallido', 'cancelado')),
  provider_message_id text,
  error text,
  scheduled_at timestamptz,
  sent_at timestamptz,
  created_by uuid references auth.users(id),
  created_at timestamptz not null default now()
);

create table if not exists public.ia_consultas (
  id uuid primary key default gen_random_uuid(),
  empresa_id uuid not null default public.current_empresa_id() references public.empresas(id) on delete cascade,
  equipo_id uuid references public.machines(id) on delete set null,
  orden_trabajo_id uuid references public.ordenes_trabajo(id) on delete set null,
  tipo text not null default 'tecnica',
  pregunta text not null,
  respuesta text,
  metadata jsonb not null default '{}'::jsonb,
  created_by uuid references auth.users(id),
  created_at timestamptz not null default now()
);
